---
  name: Feature Request
  description: Describe your feature request here.
  title: "FEAT: <Please write a comprehensive title after the 'FEAT: ' prefix>"
  labels: [Feature]

  body:
  - type: markdown
    attributes:
      value: >
        If you're looking to request a new feature or change in functionality,
        please describe the change hear.  Please include any links or related
        issues that are relevant to the feature request.

  - type: textarea
    attributes:
      label: "## Brief Description of the Proposed Feature or Change:"
    validations:
      required: true